# Generated by Django 5.1.4 on 2024-12-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userblogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userblogs',
            options={'verbose_name': 'UserBlog'},
        ),
    ]
