# Generated by Django 5.1.4 on 2024-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_date_userblogs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusers',
            name='username',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
