# Generated by Django 5.1.4 on 2024-12-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_loginusers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginusers',
            name='username',
        ),
    ]
