# Generated by Django 5.1.4 on 2025-01-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_loginusers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogs',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
