# Generated by Django 5.1.4 on 2025-01-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_userblogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblogs',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
