# Generated by Django 5.1.4 on 2025-01-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_userblogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
