# Generated by Django 5.1.4 on 2025-01-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_userblogs_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creared_at', models.TimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.userblogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.loginusers')),
            ],
            options={
                'verbose_name': 'Like',
                'unique_together': {('user', 'blog')},
            },
        ),
    ]
